export const CONFIG = {
  formSelector: '.popup__form',
  inputSelector: '.popup__input',
  submitButtonSelector: '.popup__btn-save',
  profileNameSelector: '.profile__name',
  profileAboutSelector: '.profile__about',
  profileAvatarSelector: '.profile__avatar-img',
  popupImageSelector: '.popup-image',
  popupNewImageSelector: '.popup-newImage',
  popupProfileSelector: '.popup-profile',
  popupAgreeSelector: '.popup-agreeDelete',
  popupNewAvatarSelector: '.popup-newAvatar',
  gallerySelector: '.gallery',
  inactiveButtonClass: 'popup__btn-inactive',
  activeButtonClass: 'popup__btn-save',
  inputErrorClass: 'popup__input_type_error',
  errorClass: 'popup__error-message_active',
  templateSelector: '#template-gallery',
};